title: "Kosen Sangha — Publications & Plannings"
description: "LaTeX publishing toolchain for the publications of Master Kosen and Kosen Sangha."
theme: jekyll-theme-primer
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
